# Generated by Django 4.1.2 on 2022-10-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medication',
            field=models.ManyToManyField(to='main_app.medication'),
        ),
    ]
